name: Run tests

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: "Run tests"
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.0"
            graphql-ruby: "1.12"
            interpreter: yes
          - ruby: "3.0"
            graphql-ruby: "1.12"
            interpreter: no
          - ruby: "2.7"
            graphql-ruby: "1.11"
            interpreter: yes
          - ruby: "2.7"
            graphql-ruby: "1.11"
            interpreter: no
          - ruby: "2.6"
            graphql-ruby: "1.10"
            interpreter: yes
          - ruby: "2.6"
            graphql-ruby: "1.10"
            interpreter: no
          - ruby: "2.5"
            graphql-ruby: "1.9"
            interpreter: yes
          - ruby: "2.5"
            graphql-ruby: "1.9"
            interpreter: no
    container:
      image: ruby:${{ matrix.ruby }}
      env:
        CI: true
        GRAPHQL_RUBY_INTERPRETER: ${{ matrix.interpreter }}
        BUNDLE_GEMFILE: gemfiles/graphql_${{ matrix.graphql-ruby }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ matrix.ruby }}-${{ matrix.graphql-ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            bundle-${{ matrix.ruby }}-${{ matrix.graphql-ruby }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
            bundle-${{ matrix.ruby }}-
      - name: Upgrade Bundler to 2.x (for older Rubies)
        run: gem install bundler -v '~> 2.0'
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
          bundle update
      - name: Run RSpec
        run: bundle exec rspec
